name:  Shell Commands

# push,pull etc
on: [push] 

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hello Github Action" 

      - name: multiline scripts
        run: |
          node -v
          npm -v
