name: Shell Commands

# push,pull etc
on: [push]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hello Github Action"
      - name: multiline scripts
        run: |
          node -v
          npm -v
      - name: python script
        run: |
          import platform
          print
          (platform.processor())
        shell: python

  run-windows-command:
    runs-on: windows-latest
    # waiting for run-shell-command complete
    needs: ["run-shell-command"]
    steps:
      - name: Directory Powershell
        run: Get-Location
      - name: Directory Bash
        run: pwd
        shell: bash
